# Generated by Django 5.2.13 on 2026-04-16 15:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Crianca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('data_nascimento', models.DateField(verbose_name='Data de Nascimento')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='criancas/', verbose_name='Foto')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('psicologo', models.ForeignKey(limit_choices_to={'role': 'psicologo'}, on_delete=django.db.models.deletion.CASCADE, related_name='criancas_psicologo', to=settings.AUTH_USER_MODEL)),
                ('responsaveis', models.ManyToManyField(blank=True, limit_choices_to={'role': 'responsavel'}, related_name='criancas_responsavel', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Criança',
                'verbose_name_plural': 'Crianças',
                'ordering': ['nome'],
            },
        ),
    ]
