# Generated by Django 5.2.13 on 2026-04-16 15:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Atividade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('pergunta', models.CharField(help_text='Ex: Quem está feliz?', max_length=300, verbose_name='Pergunta')),
                ('emocao_correta', models.CharField(choices=[('feliz', 'Feliz'), ('triste', 'Triste'), ('raiva', 'Raiva'), ('medo', 'Medo'), ('surpresa', 'Surpresa'), ('nojo', 'Nojo'), ('neutro', 'Neutro')], max_length=20, verbose_name='Emoção Correta')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('psicologo', models.ForeignKey(limit_choices_to={'role': 'psicologo'}, on_delete=django.db.models.deletion.CASCADE, related_name='atividades', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Atividade',
                'verbose_name_plural': 'Atividades',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ImagemEmocao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='emocoes/', verbose_name='Imagem')),
                ('emocao', models.CharField(choices=[('feliz', 'Feliz'), ('triste', 'Triste'), ('raiva', 'Raiva'), ('medo', 'Medo'), ('surpresa', 'Surpresa'), ('nojo', 'Nojo'), ('neutro', 'Neutro')], max_length=20, verbose_name='Emoção')),
                ('ordem', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('atividade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagens', to='atividades.atividade')),
            ],
            options={
                'verbose_name': 'Imagem de Emoção',
                'verbose_name_plural': 'Imagens de Emoção',
                'ordering': ['ordem'],
            },
        ),
    ]
