# Generated by Django 5.2.13 on 2026-10-05 18:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atividades', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AtividadeCartoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('psicologo', models.ForeignKey(limit_choices_to={'role': 'psicologo'}, on_delete=django.db.models.deletion.CASCADE, related_name='atividades_cartoes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Atividade de Cartões',
                'verbose_name_plural': 'Atividades de Cartões',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CartaoEmocao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('palavra', models.CharField(help_text='Texto exibido no cartão. Ex: Feliz', max_length=50, verbose_name='Palavra')),
                ('imagem', models.ImageField(upload_to='cartoes/', verbose_name='Imagem')),
                ('emocao', models.CharField(choices=[('feliz', 'Feliz'), ('triste', 'Triste'), ('raiva', 'Raiva'), ('medo', 'Medo'), ('surpresa', 'Surpresa'), ('nojo', 'Nojo'), ('neutro', 'Neutro')], max_length=20, verbose_name='Emoção')),
                ('ordem', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('atividade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cartoes', to='atividades.atividadecartoes')),
            ],
            options={
                'verbose_name': 'Cartão de Emoção',
                'verbose_name_plural': 'Cartões de Emoção',
                'ordering': ['ordem', 'id'],
            },
        ),
    ]
