# Generated by Django 5.2.13 on 2026-10-05 20:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atividades', '0002_atividadecartoes_cartaoemocao'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AtividadeCenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('psicologo', models.ForeignKey(limit_choices_to={'role': 'psicologo'}, on_delete=django.db.models.deletion.CASCADE, related_name='atividades_cenarios', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Atividade de Cenários',
                'verbose_name_plural': 'Atividades de Cenários',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CenarioEmocao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='cenarios/', verbose_name='Imagem do cenário')),
                ('descricao', models.CharField(help_text='Ex: A criança ganhou um bolo de aniversário.', max_length=300, verbose_name='Descrição da situação')),
                ('emocao_correta', models.CharField(choices=[('feliz', 'Feliz'), ('triste', 'Triste'), ('raiva', 'Raiva'), ('medo', 'Medo'), ('surpresa', 'Surpresa'), ('nojo', 'Nojo'), ('neutro', 'Neutro')], max_length=20, verbose_name='Emoção Correta')),
                ('ordem', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('atividade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cenarios', to='atividades.atividadecenario')),
            ],
            options={
                'verbose_name': 'Cenário de Emoção',
                'verbose_name_plural': 'Cenários de Emoção',
                'ordering': ['ordem', 'id'],
            },
        ),
    ]
