# Generated by Django 5.2.13 on 2026-04-16 15:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('atividades', '0001_initial'),
        ('criancas', '0001_initial'),
        ('sessoes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Desempenho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correto', models.BooleanField(verbose_name='Acertou')),
                ('tempo_resposta', models.FloatField(blank=True, null=True, verbose_name='Tempo de Resposta (s)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('atividade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='desempenhos', to='atividades.atividade')),
                ('crianca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='desempenhos', to='criancas.crianca')),
                ('executado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='desempenhos_registrados', to=settings.AUTH_USER_MODEL)),
                ('imagem_selecionada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='atividades.imagememocao')),
                ('sessao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='desempenhos', to='sessoes.sessao')),
            ],
            options={
                'verbose_name': 'Desempenho',
                'verbose_name_plural': 'Desempenhos',
                'ordering': ['-created_at'],
            },
        ),
    ]
