# Generated by Django 5.2.13 on 2026-10-05 18:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atividades', '0002_atividadecartoes_cartaoemocao'),
        ('criancas', '0001_initial'),
        ('desempenho', '0001_initial'),
        ('sessoes', '0002_sessao_atividades_cartoes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DesempenhoCartoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correto', models.BooleanField(verbose_name='Acertou')),
                ('tempo_resposta', models.FloatField(blank=True, null=True, verbose_name='Tempo de Resposta (s)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('atividade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='desempenhos', to='atividades.atividadecartoes')),
                ('cartao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='atividades.cartaoemocao', verbose_name='Cartão (palavra)')),
                ('cartao_selecionado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='atividades.cartaoemocao', verbose_name='Imagem selecionada')),
                ('crianca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='desempenhos_cartoes', to='criancas.crianca')),
                ('executado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='desempenhos_cartoes_registrados', to=settings.AUTH_USER_MODEL)),
                ('sessao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='desempenhos_cartoes', to='sessoes.sessao')),
            ],
            options={
                'verbose_name': 'Desempenho (Cartões)',
                'verbose_name_plural': 'Desempenhos (Cartões)',
                'ordering': ['-created_at'],
            },
        ),
    ]
