# Generated by Django 5.2.13 on 2026-10-05 20:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atividades', '0003_atividadecenario_cenarioemocao'),
        ('criancas', '0001_initial'),
        ('desempenho', '0002_desempenhocartoes'),
        ('sessoes', '0003_sessao_atividades_cenarios'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DesempenhoCenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emocao_selecionada', models.CharField(choices=[('feliz', 'Feliz'), ('triste', 'Triste'), ('raiva', 'Raiva'), ('medo', 'Medo'), ('surpresa', 'Surpresa'), ('nojo', 'Nojo'), ('neutro', 'Neutro')], max_length=20, verbose_name='Emoção selecionada')),
                ('correto', models.BooleanField(verbose_name='Acertou')),
                ('tempo_resposta', models.FloatField(blank=True, null=True, verbose_name='Tempo de Resposta (s)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('atividade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='desempenhos', to='atividades.atividadecenario')),
                ('cenario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='atividades.cenarioemocao')),
                ('crianca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='desempenhos_cenarios', to='criancas.crianca')),
                ('executado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='desempenhos_cenarios_registrados', to=settings.AUTH_USER_MODEL)),
                ('sessao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='desempenhos_cenarios', to='sessoes.sessao')),
            ],
            options={
                'verbose_name': 'Desempenho (Cenários)',
                'verbose_name_plural': 'Desempenhos (Cenários)',
                'ordering': ['-created_at'],
            },
        ),
    ]
