# Generated by Django 5.2.13 on 2026-04-16 15:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('atividades', '0001_initial'),
        ('criancas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sessao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('data_sessao', models.DateField(blank=True, null=True, verbose_name='Data da Sessão')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('psicologo', models.ForeignKey(limit_choices_to={'role': 'psicologo'}, on_delete=django.db.models.deletion.CASCADE, related_name='sessoes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sessão',
                'verbose_name_plural': 'Sessões',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SessaoAtividade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('atividade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atividades.atividade')),
                ('sessao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sessoes.sessao')),
            ],
            options={
                'ordering': ['ordem'],
                'unique_together': {('sessao', 'atividade')},
            },
        ),
        migrations.AddField(
            model_name='sessao',
            name='atividades',
            field=models.ManyToManyField(blank=True, related_name='sessoes', through='sessoes.SessaoAtividade', to='atividades.atividade'),
        ),
        migrations.CreateModel(
            name='SessaoCrianca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crianca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='criancas.crianca')),
                ('sessao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sessoes.sessao')),
            ],
            options={
                'unique_together': {('sessao', 'crianca')},
            },
        ),
        migrations.AddField(
            model_name='sessao',
            name='criancas',
            field=models.ManyToManyField(blank=True, related_name='sessoes', through='sessoes.SessaoCrianca', to='criancas.crianca'),
        ),
    ]
