# Generated by Django 5.2.13 on 2026-10-05 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atividades', '0002_atividadecartoes_cartaoemocao'),
        ('sessoes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessao',
            name='atividades_cartoes',
            field=models.ManyToManyField(blank=True, related_name='sessoes', to='atividades.atividadecartoes', verbose_name='Atividades de Cartões'),
        ),
    ]
