# Generated by Django 5.2.13 on 2026-10-05 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atividades', '0003_atividadecenario_cenarioemocao'),
        ('sessoes', '0002_sessao_atividades_cartoes'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessao',
            name='atividades_cenarios',
            field=models.ManyToManyField(blank=True, related_name='sessoes', to='atividades.atividadecenario', verbose_name='Atividades de Cenários'),
        ),
    ]
